### ISSUE TITLE
Complete Generate rename and open source

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/mi-label#4]

**Comment by rchenatjpl** [comment]
I hate to open an issue for this. The download link on https://nasa-pds.github.io/mi-label/ doesn't work:
https://pds.nasa.gov/software/pds4/mi-label-1.1.0-bin.tar.gz
<img width="518" alt="Screen Shot 2020-05-07 at 15 42 20" src="https://user-images.githubusercontent.com/56557532/81351842-1458df80-907a-11ea-9085-58346e02085d.png">
